language: python
python:
    - "2.7"
install:
    - pip install pep8
    - pip install -r requirements.txt
    - pip install -e .
    - pip install -r tests/requirements.txt
script:
    - pep8 --ignore=E501 .
    - coverage run --source=oauth2py tests/test.py
after_success:
    - coveralls
